[package]
name = "rfs-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow ="1.0"
core = { path = "../../crates/core" }
db = { path = "../../crates/db" }
net = { path = "../../crates/net" }
scripts = { path = "../../crates/scripts" }
