[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
world = { path = "../world" }
entities = { path = "../entities" }
items = { path = "../items" }
scripting = { path = "../scripting" }
