[package]
name = "protocols-game"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
net = { path = "../../net" }
world = { path = "../../world" }
entities = { path = "../../entities" }
items = { path = "../../items" }
