[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]

thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
once_cell = "1.19"
mlua = { version = "0.9", features = ["lua54", "serialize"] }
serde = { version = "1.0", features = ["derive"] }